version = 1
SPDX-PackageName = "iron"
SPDX-PackageSupplier = "Advanced Micro Devices, Inc."
SPDX-PackageDownloadLocation = "https://github.com/amd/IRON"

[[annotations]]
path = "iron/applications/common/prompt.txt"
precedence = "closest"
SPDX-FileCopyrightText = "Public Domain"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["iron/applications/llama3/profiles/*.json", "iron/tests/common/*.json"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved."
SPDX-License-Identifier = "Apache-2.0"
