version = 1
SPDX-PackageName = "iron"
SPDX-PackageSupplier = "Advanced Micro Devices, Inc."
SPDX-PackageDownloadLocation = "https://github.com/amd/IRON"

[[annotations]]
path = "iron/lm/prompt.txt"
precedence = "closest"
SPDX-FileCopyrightText = "Public Domain"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "iron/lm/llama3/profiles/*.json",
    "iron/lm/llama3/costs_*.json",
    "iron/lm/embeddinggemma2/vision/profiles/*.json",
    "iron/lm/embeddinggemma2/costs_*.json",
    "iron/lm/embeddinggemma2/vision/costs_*.json",
    "iron/lm/embeddinggemma2/audio/costs_*.json",
    "iron/tests/common/*.json",
]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved."
SPDX-License-Identifier = "Apache-2.0"
