# SPDX-FileCopyrightText: Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import torch
import numpy as np
from ml_dtypes import bfloat16
from pathlib import Path

from iron.common import (
    AIEOperatorBase,
    AIEOperatorConstraintError,
    XclbinArtifact,
    InstsBinArtifact,
    KernelObjectArtifact,
    SourceArtifact,
    PythonGeneratedMLIRArtifact,
)
from iron.common.utils import torch_to_numpy


class AIEFusedDequantGEMV(AIEOperatorBase):
    """AIE-accelerated fused INT4 dequantization + matrix-vector multiplication.

    Loads INT4-packed weights from DDR, dequantizes in-register, and computes
    the matrix-vector product in a single pass.  This achieves 4x DDR
    bandwidth reduction compared to streaming bf16 weights.

    The packed weight buffer layout (generated by the reference module's
    ``quantize_and_pack``) is tile-based.  Each tile covers ``m_input`` rows
    and is structured as:

        [m_input * K / 2 bytes]  packed uint4 weights
        [m_input * (K / group_size) * 2 bytes]  bf16 scale factors

    Tiles are grouped per column: column 0 tiles first, then column 1, etc.
    """

    def __init__(
        self,
        M,
        K,
        num_aie_columns=4,
        tile_size_input=1,
        tile_size_output=None,
        group_size=32,
        context=None,
    ):
        if tile_size_output is None:
            tile_size_output = M // num_aie_columns

        assert (
            tile_size_output % tile_size_input == 0
            and tile_size_output >= tile_size_input
        ), "tile_size_output must be a multiple of tile_size_input"
        assert K % group_size == 0, "K must be a multiple of group_size"
        assert group_size % 32 == 0, "group_size must be a multiple of 32"
        assert M % num_aie_columns == 0, "M must be a multiple of num_aie_columns"

        self.M = M
        self.K = K
        self.num_aie_columns = num_aie_columns
        self.tile_size_input = tile_size_input
        self.tile_size_output = tile_size_output
        self.group_size = group_size

        self.xclbin_artifact = None
        self.insts_artifact = None

        AIEOperatorBase.__init__(self, context=context)

    def _packed_buffer_size(self):
        """Total DDR buffer size in uint8 bytes."""
        num_groups_per_row = self.K // self.group_size
        packed_tile_bytes = (
            self.tile_size_input * self.K // 2
            + self.tile_size_input * num_groups_per_row * 2
        )
        rows_per_col = self.M // self.num_aie_columns
        tiles_per_col = rows_per_col // self.tile_size_input
        return self.num_aie_columns * tiles_per_col * packed_tile_bytes

    def get_artifacts(self, prefix="fused_dequant_gemv_"):
        operator_dir = Path(__file__).parent
        file_name_base = (
            f"{prefix}{self.M}x{self.K}"
            f"_{self.tile_size_input}tsi"
            f"_{self.tile_size_output}tso"
            f"_{self.num_aie_columns}col"
            f"_g{self.group_size}"
        )

        mlir_artifact = PythonGeneratedMLIRArtifact.new(
            f"{file_name_base}.mlir",
            import_path=operator_dir / "design.py",
            callback_fn="my_fused_dequant_matvec",
            callback_args=[
                self.context.device_manager.device_type,
                self.num_aie_columns,
                self.M,
                self.K,
                self.tile_size_input,
                self.tile_size_output,
                self.group_size,
            ],
        )

        xclbin_artifact = XclbinArtifact.new(
            f"{file_name_base}.xclbin",
            depends=[
                mlir_artifact,
                KernelObjectArtifact.new(
                    "fused_dequant_gemv.o",
                    depends=[
                        SourceArtifact.new(
                            self.context.base_dir
                            / "aie_kernels"
                            / "aie2p"
                            / "fused_dequant_gemv.cc"
                        )
                    ],
                ),
            ],
        )

        insts_artifact = InstsBinArtifact.new(
            f"{file_name_base}.bin", depends=[mlir_artifact]
        )

        return xclbin_artifact, insts_artifact

    def set_up_artifacts(self):
        xclbin_artifact, insts_artifact = self.get_artifacts()
        self.xclbin_artifact = xclbin_artifact
        self.insts_artifact = insts_artifact
        self.add_artifacts([xclbin_artifact, insts_artifact])

    def set_up_runtime(self):
        # Packed weights buffer uses uint8 dtype
        self.add_buffer(
            "packed_weights",
            self._packed_buffer_size(),
            dtype=np.uint8,
        )
        # Input vector and output vector use bfloat16
        self.add_buffer("vector", self.K, dtype=bfloat16)
        self.add_buffer("output", self.M, dtype=bfloat16)
        self.add_kernel(
            "fused_dequant_gemv",
            self.xclbin_artifact,
            self.xclbin_artifact.kernel_name,
            self.insts_artifact,
        )
        self.add_to_runlist("fused_dequant_gemv", "packed_weights", "vector", "output")

    def forward(self, vector, packed_weights=None):
        """Forward pass: fused INT4 dequant + matrix-vector multiplication.

        Args:
            vector: Input vector of shape (K,), dtype torch.bfloat16.
            packed_weights: Optional numpy uint8 array of packed INT4
                weights.  If None, assumes weights were already written
                to the buffer.

        Returns:
            Output vector of shape (M,), dtype torch.bfloat16.
        """
        vector = vector.reshape(*vector.shape[-1:])

        if vector.shape[-1] != self.K or vector.dtype != torch.bfloat16:
            raise AIEOperatorConstraintError(
                f"AIEFusedDequantGEMV: expected bf16 vector of length "
                f"{self.K}, got shape {vector.shape} dtype {vector.dtype}"
            )

        if packed_weights is not None:
            self.write_buffer("packed_weights", packed_weights)
        self.write_buffer("vector", vector)
        self.run_runlist()
        result = self.read_buffer_as_torch("output", (self.M,))
        return result
