# SPDX-FileCopyrightText: Copyright (C) 2026 KU Leuven (MICAS). All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from dataclasses import dataclass, field
from typing import Any

import aie.utils as aie_utils
import torch

from iron.common.sequence import OperatorSequence
from iron.common.stream.group import StreamGroup


@dataclass
class _MHAStreamGroup(StreamGroup):
    """One stream-dse design as an ``OperatorSequence`` child: group ``group_index`` of
    the ``k`` the attention core is split into, ordered as ``stream_design.group_layers``.
    """

    seq_len: int
    d_head: int
    heads: int
    k: int
    group_index: int
    causal: bool = False
    flash: bool = False
    query_block: int | None = None
    context: Any = field(default=None, repr=False, compare=False)

    def __post_init__(self):
        StreamGroup.__init__(self, context=self.context)

    @property
    def _design(self):
        from iron.operators.mha_prefill_stream import stream_design

        return stream_design

    def _dims(self):
        return {
            "k": self.k,
            "seq_len": self.seq_len,
            "d_head": self.d_head,
            "heads": self.heads,
            "causal": self.causal,
            "flash": self.flash,
            "query_block": self.query_block,
            "npu": aie_utils.get_current_device().resolve().name,
        }

    def reference(self, *inputs):
        """CPU result for this group: its layers in order, each GEMM taking the group's
        next input (in :func:`group_ports` order) as its second operand."""
        from iron.operators.mha_prefill_stream.reference import causal_mask

        design = self._design
        value, operands = inputs[0], iter(inputs[1:])
        for layer in design.group_layers(self.k)[self.group_index]:
            if layer == design.SOFTMAX_NODE:
                scores = value.float()
                if self.causal:
                    scores = scores + causal_mask(*scores.shape[-2:], scores.dtype)
                value = torch.softmax(scores, dim=-1).to(value.dtype)
            else:
                value = value @ next(operands)
        return value

    def _ports(self):
        dims = (self.seq_len, self.d_head, self.heads)
        return (
            self._design.workload_for(*dims).shapes,
            self._design.group_ports(*dims, self.k)[self.group_index],
        )


class MHAPrefillStream(OperatorSequence):
    """Prefill attention ``softmax(q @ k_t) @ v`` per head, generated by stream-dse, over
    a pre-scaled ``q`` and a pre-transposed ``k_t``. ``flash`` blocks the key (always causal);
    ``query_block`` pins its query block, else stream picks. See ``README.md``."""

    def __init__(
        self,
        seq_len,
        d_head,
        heads=1,
        k=None,
        causal=False,
        flash=False,
        context=None,
        share_designs=True,
        dispatch="auto",
        query_block=None,
    ):
        from iron.common.stream.design import trace_size
        from iron.operators.mha_prefill_stream.stream_design import (
            LAYER_BY_LAYER,
            group_ports,
        )

        if query_block is not None and not flash:
            raise ValueError(
                "query_block pins the flash query block, so it needs flash"
            )
        k = (1 if flash else LAYER_BY_LAYER) if k is None else k
        causal = causal or flash
        runlist = [
            (
                _MHAStreamGroup(
                    seq_len=seq_len,
                    d_head=d_head,
                    heads=heads,
                    k=k,
                    group_index=index,
                    causal=causal,
                    flash=flash,
                    query_block=query_block,
                    context=context,
                ),
                *inputs,
                *outputs,
            )
            for index, (inputs, outputs) in enumerate(
                group_ports(seq_len, d_head, heads, k)
            )
        ]
        super().__init__(
            name=(
                f"mha_prefill_stream_k{k}_h{heads}_s{seq_len}_d{d_head}"
                f"{'_flash' if flash else '_causal' if causal else ''}"
                f"{'' if query_block is None else f'_q{query_block}'}"
            ),
            runlist=runlist,
            input_args=["q", "k_t", "v"],
            output_args=["output"],
            trace_size=trace_size(),
            share_designs=share_designs,
            dispatch=dispatch,
            context=context,
        )
