#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import re
import sys
import csv
import math
import argparse
import subprocess
from datetime import datetime

from pathlib import Path
from importlib.util import spec_from_file_location, module_from_spec


def mean(l):
    return sum(l) / len(l)


def median(l):
    l_sorted = sorted(l)
    middle = len(l) // 2
    if len(l) % 2 == 1:
        return l_sorted[middle]
    return (l_sorted[middle - 1] + l_sorted[middle]) / 2.0


def stddev(l):
    m = mean(l)
    return math.sqrt(sum((x - m) ** 2 for x in l) / len(l))


def write_results(output_rows, path):
    output_rows.sort(key=lambda x: (x["Test"], x["Date"]))
    cols = {}  # we use a dict rather than a set because it guarantees insertion order
    for row in output_rows:
        cols.update({k: None for k in row.keys()})
    with open(path, "w", newline="") as f:
        if output_rows:
            writer = csv.DictWriter(f, cols.keys())
            writer.writeheader()
            writer.writerows(output_rows)


def run_test(test_name, test_path, iters: int, verbose=False, log_f=None):
    """Run a single test script."""
    script_path = Path(test_path) / f"{test_name}.py"

    # Check if the script exists
    if not script_path.exists():
        print(f"❌ Test script not found: {script_path}")
        return False

    print(f"🔄 Running test: {test_name}")
    print(f"   Path: {script_path}")

    try:

        spec = spec_from_file_location("test_module", script_path)
        test_module = module_from_spec(spec)
        spec.loader.exec_module(test_module)

        command = test_module.run
        metrics = test_module.metrics

        metrics_list = []
        ret_code_list = []

        for _ in range(iters):

            if log_f:
                log_f.flush()
                log_f.write("\n\n")
                log_f.write("=" * 80 + "\n")
                log_f.write(f"Running {test_name} ({test_path})\n")
                log_f.write("=" * 80 + "\n\n")

            result = subprocess.run(
                command,
                cwd=test_path,
                shell=True,
                capture_output=True,
                text=True,
                timeout=300,
            )

            if verbose:
                print(f"\nCommand: {command}")
                print(f"\n{result.stdout}")

            if log_f:
                log_f.write("stdout:\n")
                log_f.write(result.stdout)
                log_f.write("\nstderr:\n")
                log_f.write(result.stderr)

            metrics_dict = {}
            for metric_name, metric_regex in metrics:
                match = re.search(metric_regex, result.stdout)
                if match:
                    metrics_dict[metric_name] = float(match.group("metric"))

            metrics_list.append(metrics_dict)
            ret_code_list.append(result.returncode)

        if all(ret_code_list) == 0:
            print(f"✅ {test_name} - PASSED")
            return (ret_code_list, metrics_list)
        else:
            print(f"❌ {test_name} - FAILED")
            print(f"   Stdout: {result.stdout}")
            print(f"   Stderr: {result.stderr}")
            return (ret_code_list, metrics_list)

    except subprocess.TimeoutExpired:
        print(f"⏰ {test_name} - TIMEOUT")
        return (-1, None)
    except Exception as e:
        print(f"💥 {test_name} - ERROR: {e}")
        return (-1, None)


def get_git_commit():
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except Exception:
        return "unknown"


def main():
    """Run all tests and report results."""

    parser = argparse.ArgumentParser(description="Run CI tests generated by CMake.")
    parser.add_argument(
        dest="build_dir",
        default="build",
        help="IRONCLAD build directory containing ci_tests.py",
    )
    parser.add_argument(
        "--log",
        default="test_run_{}.log",
        help="File to log test command outputs to. {} is replaced with the current date.",
    )
    parser.add_argument(
        "--csv-latest",
        default="tests_latest.csv",
        help="Path to output CSV for this runs results, {} is replaced with the current date.",
    )
    parser.add_argument(
        "--iters",
        default=5,
        type=int,
        help="Number of iterations to run of each test for metrics",
    )
    parser.add_argument(
        "-t",
        "--select",
        default=[],
        action="append",
        help="Select single test to execute. Can be passed multiple times to select multiple tests. Default: all tests.",
    )
    parser.add_argument(
        "-v", "--verbose", action="store_true", help="Enable verbose output"
    )
    args, unknown = parser.parse_known_args()
    verbose = args.verbose

    old_sys_path = sys.path
    sys.path.append(str(Path(args.build_dir).absolute()))
    import ci_tests as input_ci_tests

    sys.path = old_sys_path

    ci_tests = input_ci_tests.tests
    ci_paths = input_ci_tests.paths

    print("Starting test run...")
    print(f"Total tests: {len(ci_tests)}")
    print("-" * 50)

    now = datetime.now()
    commit = get_git_commit()
    results = []
    passed = 0
    failed = 0

    log_f = None
    if args.log:
        log_file = args.log.format(now.strftime("%Y_%m_%d_%H_%M_%S"))
        log_f = open(log_file, "w")
        # Don't worry about closing log_f, we'll keep it open for the entire program execution anyways

    n_tests = 0
    for test_name, test_path in zip(ci_tests, ci_paths):
        if args.select and test_name not in args.select:
            continue
        n_tests += 1

        row = {
            "Commit": commit,
            "Date": now.strftime("%Y-%m-%d %H:%M:%S"),
            "Test": test_name,
        }

        retcode_list, metrics_list = run_test(
            test_name, test_path, args.iters, verbose=args.verbose, log_f=log_f
        )
        if all(retcode_list) == 0:
            passed += 1
        else:
            failed += 1
        print()

        row["Checks"] = f"{retcode_list.count(0)}/{len(retcode_list)}"

        stats = [
            ("mean", mean),
            ("median", median),
            ("min", min),
            ("max", max),
            ("stddev", stddev),
        ]

        metric_names = set()
        for metric_dict in metrics_list:
            metric_names.update(metric_dict.keys())

        for metric_name in metric_names:
            values = [d[metric_name] for d in metrics_list if metric_name in d]
            if values:
                for stat_name, stat_fun in stats:
                    row[f"{metric_name} ({stat_name})"] = stat_fun(values)

        results.append(row)

    # Summary
    print("-" * 50)
    print(f"Test Results:")
    print(f"  ✅ Passed: {passed}")
    print(f"  ❌ Failed: {failed}")
    print(f"  📊 Total:  {n_tests}")

    if args.csv_latest:
        csv_latest_path = args.csv_latest.format(now.strftime("%Y_%m_%d_%H_%M_%S"))
        write_results(results, csv_latest_path)

    if failed == 0:
        print("🎉 All tests passed!")
        return 0
    else:
        print(f"💔 {failed} test(s) failed")
        return 1


if __name__ == "__main__":
    sys.exit(main())
