# SPDX-FileCopyrightText: Copyright (C) 2026 KU Leuven (MICAS). All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import functools

import aie.utils as aie_utils
from aie.utils.trace import TraceConfig
from ml_dtypes import bfloat16

from iron.common import In, Operator, Out, param
from iron.common.image import OperatorSequence

# stream-dse is optional: importing the operator does not need it, building does.
try:
    from iron.operators.swiglu_prefill_stream import stream_design
except ModuleNotFoundError as missing:
    stream_design = None
    _MISSING = missing


def _stream_design():
    if stream_design is None:
        raise ModuleNotFoundError(
            "swiglu_prefill_stream is generated by stream-dse "
            "(pip install stream-dse + stream-setup-aie)"
        ) from _MISSING
    return stream_design


class SwiGLUStreamGroup(Operator):
    """One stream-dse design: a fused group of the SwiGLU-prefill block.

    ``k`` is how many fused groups the block is split into and
    ``group_index`` which of them this is, in the order
    :data:`~iron.operators.swiglu_prefill_stream.stream_design.GROUP_LAYERS`
    lists them. A subclass per group declares its ports, named by the
    exported graph's tensors (S = ``seq_len``, E = ``embedding_dim``,
    H = ``hidden_dim``) in the order stream-dse gives the generated design
    its arguments. The design is the exported text, not derived from the
    declaration, and groups whose text is byte-identical share it.
    """

    seq_len: int = param()
    embedding_dim: int = param()
    hidden_dim: int = param()
    k: int = param()
    group_index: int = param()

    def _dims(self) -> dict:
        return dict(
            group_index=self.group_index,
            k=self.k,
            seq_len=self.seq_len,
            embedding_dim=self.embedding_dim,
            hidden_dim=self.hidden_dim,
            npu=aie_utils.ensure_current_device(required=True).name,
            trace_size=0 if self.trace is None else self.trace.trace_size,
        )

    def design_key(self):
        return _stream_design().group_digest(**self._dims())

    def exported_design(self, image: str):
        return functools.partial(_stream_design().load_group, **self._dims())

    @classmethod
    def for_ports(cls, inputs, outputs) -> type["SwiGLUStreamGroup"]:
        """The group class whose ports are ``inputs`` then ``outputs``."""
        for group in cls.__subclasses__():
            ins = [m.name for m in group._members if isinstance(m, In)]
            outs = [m.name for m in group._members if isinstance(m, Out)]
            if (ins, outs) == (list(inputs), list(outputs)):
                return group
        raise NotImplementedError(
            f"no SwiGLUStreamGroup takes {inputs} and gives {outputs}; "
            f"the exported graph's group ports changed"
        )


S = SwiGLUStreamGroup.seq_len
E = SwiGLUStreamGroup.embedding_dim
H = SwiGLUStreamGroup.hidden_dim


class Block(SwiGLUStreamGroup):
    """The whole block in one design (``k=1``)."""

    input = In(S, E, dtype=bfloat16)
    w_gate = In(E, H, dtype=bfloat16)
    w_up = In(E, H, dtype=bfloat16)
    w_down = In(H, E, dtype=bfloat16)
    output = Out(S, E, dtype=bfloat16)


class GateUp(SwiGLUStreamGroup):
    """Both projections, the activation and the product (``k=2``'s first)."""

    input = In(S, E, dtype=bfloat16)
    w_gate = In(E, H, dtype=bfloat16)
    w_up = In(E, H, dtype=bfloat16)
    intermediate = Out(S, H, dtype=bfloat16)


class Down(SwiGLUStreamGroup):
    """The down projection."""

    intermediate = In(S, H, dtype=bfloat16)
    w_down = In(H, E, dtype=bfloat16)
    output = Out(S, E, dtype=bfloat16)


class Gate(SwiGLUStreamGroup):
    """The gate projection alone (layer by layer)."""

    input = In(S, E, dtype=bfloat16)
    w_gate = In(E, H, dtype=bfloat16)
    left = Out(S, H, dtype=bfloat16)


class Up(SwiGLUStreamGroup):
    """The up projection alone (layer by layer)."""

    input = In(S, E, dtype=bfloat16)
    w_up = In(E, H, dtype=bfloat16)
    right = Out(S, H, dtype=bfloat16)


class Swish(SwiGLUStreamGroup):
    """SiLU of the gate projection (layer by layer)."""

    left = In(S, H, dtype=bfloat16)
    left_swished = Out(S, H, dtype=bfloat16)


class Combine(SwiGLUStreamGroup):
    """The activated gate times the up projection (layer by layer)."""

    left_swished = In(S, H, dtype=bfloat16)
    right = In(S, H, dtype=bfloat16)
    intermediate = Out(S, H, dtype=bfloat16)


class SwiGLUPrefillStream(OperatorSequence):
    """SwiGLU-prefill block generated by stream-dse and deployed as one full ELF.

    ``k`` is how many fused groups the block is split into: 1 keeps the whole block
    on the array at once, 2 splits after the elementwise multiply, and 5 runs layer
    by layer, each layer taking the whole array in turn as
    :class:`iron.operators.SwiGLU` does. The split is decided by the mapping's
    fused groups, and the external buffers are the same either way. With
    ``trace``, stream-dse generates every group traced.

    Runtime buffers (``get_callable().get_buffer(name)``) are named by the reference
    module: ``input``, ``w_gate``, ``w_up``, ``w_down``, ``output``. Building
    requires ``stream-dse`` (``pip install stream-dse`` + ``stream-setup-aie``);
    importing this module does not.
    """

    def __init__(
        self,
        seq_len,
        embedding_dim,
        hidden_dim,
        k=1,
        share_designs=True,
        trace: TraceConfig | None = None,
    ):
        design = _stream_design()
        # Each group's ports, in the order the exported graph uses them. The
        # block's own arguments are what no group produces and what none
        # consumes.
        boundaries = design.group_ports(seq_len, embedding_dim, hidden_dim, k)
        produced = {name for _, outputs in boundaries for name in outputs}
        consumed = {name for inputs, _ in boundaries for name in inputs}
        runlist = [
            (
                SwiGLUStreamGroup.for_ports(inputs, outputs)(
                    seq_len=seq_len,
                    embedding_dim=embedding_dim,
                    hidden_dim=hidden_dim,
                    k=k,
                    group_index=index,
                    trace=trace,
                ),
                *inputs,
                *outputs,
            )
            for index, (inputs, outputs) in enumerate(boundaries)
        ]
        super().__init__(
            name=f"swiglu_prefill_stream_k{k}_m{seq_len}_e{embedding_dim}_h{hidden_dim}",
            runlist=runlist,
            input_args=list(
                dict.fromkeys(
                    n for inputs, _ in boundaries for n in inputs if n not in produced
                )
            ),
            output_args=list(
                dict.fromkeys(
                    n for _, outputs in boundaries for n in outputs if n not in consumed
                )
            ),
            share_designs=share_designs,
        )
