# SPDX-FileCopyrightText: Copyright (C) 2026 KU Leuven (MICAS). All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from dataclasses import dataclass, field
from typing import Any

import aie.utils as aie_utils

from iron.common.sequence import OperatorSequence
from iron.common.stream.group import StreamGroup


@dataclass
class _SwiGLUStreamGroup(StreamGroup):
    """One stream-dse design, used as an ``OperatorSequence`` child.

    ``k`` is how many fused groups the block is split into and ``group_index``
    which of them this is, in the order
    :data:`~iron.operators.swiglu_prefill_stream.stream_design.GROUP_LAYERS`
    lists them.
    """

    seq_len: int
    embedding_dim: int
    hidden_dim: int
    k: int | None
    group_index: int
    gemm_block: tuple[int, int, int] | None = None
    context: Any = field(default=None, repr=False, compare=False)

    def __post_init__(self):
        StreamGroup.__init__(self, context=self.context)

    @property
    def _design(self):
        from iron.operators.swiglu_prefill_stream import stream_design

        return stream_design

    def _dims(self):
        return {
            "k": self.k,
            "seq_len": self.seq_len,
            "embedding_dim": self.embedding_dim,
            "hidden_dim": self.hidden_dim,
            "npu": aie_utils.get_current_device().resolve().name,
            "gemm_block": self.gemm_block,
        }

    def _ports(self):
        dims = (self.seq_len, self.embedding_dim, self.hidden_dim)
        return (
            self._design.workload_for(*dims).shapes,
            self._design.group_ports(
                *dims, self.k, self._dims()["npu"], self.gemm_block
            )[self.group_index],
        )


def _wiring(seq_len, embedding_dim, hidden_dim, k, gemm_block):
    """Each group's arguments, and the operator's own inputs and outputs.

    A group's arguments are the tensors it consumes and produces, in the order the
    exported graph uses them. The operator's own arguments are what no group
    produces and what none consumes. Imported lazily, so only building the operator
    needs stream-dse, not importing it.
    """
    from iron.operators.swiglu_prefill_stream.stream_design import group_ports

    npu = aie_utils.get_current_device().resolve().name
    boundaries = group_ports(seq_len, embedding_dim, hidden_dim, k, npu, gemm_block)
    produced = {name for _, outputs in boundaries for name in outputs}
    consumed = {name for inputs, _ in boundaries for name in inputs}
    ports = [inputs + outputs for inputs, outputs in boundaries]
    external_inputs = dict.fromkeys(
        name for inputs, _ in boundaries for name in inputs if name not in produced
    )
    external_outputs = dict.fromkeys(
        name for _, outputs in boundaries for name in outputs if name not in consumed
    )
    return ports, list(external_inputs), list(external_outputs)


class SwiGLUPrefillStream(OperatorSequence):
    """SwiGLU-prefill block generated by stream-dse as one dispatch, in ``k`` fused groups
    (1 whole, 2 split after the multiply, 5 per layer, ``None`` priced by stream).
    ``gemm_block`` pins the (sequence, embedding, hidden) GEMM block. See README.md."""

    def __init__(
        self,
        seq_len,
        embedding_dim,
        hidden_dim,
        k=None,
        context=None,
        share_designs=True,
        gemm_block=None,
    ):
        from iron.common.stream.design import trace_size

        ports, inputs, outputs = _wiring(
            seq_len, embedding_dim, hidden_dim, k, gemm_block
        )
        groups = [
            _SwiGLUStreamGroup(
                seq_len=seq_len,
                embedding_dim=embedding_dim,
                hidden_dim=hidden_dim,
                k=k,
                group_index=index,
                gemm_block=gemm_block,
                context=context,
            )
            for index in range(len(ports))
        ]
        super().__init__(
            name=(
                f"swiglu_prefill_stream_k{'auto' if k is None else k}"
                f"{'' if gemm_block is None else '_b' + 'x'.join(map(str, gemm_block))}"
                f"_m{seq_len}_e{embedding_dim}_h{hidden_dim}"
            ),
            runlist=[
                (group, *group_ports) for group, group_ports in zip(groups, ports)
            ],
            input_args=inputs,
            output_args=outputs,
            trace_size=trace_size(),
            share_designs=share_designs,
            context=context,
        )
