#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

import time
import inspect

import pytest
import torch

# The design is generated by stream-dse at compile() time. stream-dse is an
# optional dependency (see requirements_stream.txt) absent from the default CI
# image, so skip this whole module when it is unavailable.
pytest.importorskip(
    "stream", reason="stream-dse not installed (see requirements_stream.txt)"
)

from stream.inputs.aie.mapping.make_swiglu_mapping import make_swiglu_mapping

from iron.operators.swiglu_prefill_stream.op import (
    SwiGLUPrefillStream,
    SwiGLUPrefillStreamK2,
)

# swiglu_prefill_stream shares swiglu_decode's reference: W3 @ (SiLU(W1@x)*(W2@x)).
from iron.operators.swiglu_decode.reference import generate_golden_reference
from iron.common.test_utils import verify_buffer

# The k=2 variant needs stream-dse's two-fusion-group support; skip it on older
# releases that lack the ``split_groups`` mapping option.
_STREAM_HAS_SPLIT_GROUPS = (
    "split_groups" in inspect.signature(make_swiglu_mapping).parameters
)


def get_params():
    # (seq_len, embedding_dim, hidden_dim, seq_tile, embedding_tile, hidden_tile):
    # the MILP-feasible shape on the whole-array Strix (npu2) target.
    return [pytest.param(256, 512, 2048, 32, 32, 64)]


def _run_and_verify(operator, seq_len, embedding_dim, golden_ref):
    operator.compile()
    run = operator.get_callable()

    # Populate inputs by name; the design consumes weights in their natural
    # (K, N) layout (no transpose).
    run.get_buffer("input").torch_view()[:] = (
        golden_ref["input"].to(torch.bfloat16).flatten()
    )
    run.get_buffer("weights_1").torch_view()[:] = (
        golden_ref["w_gate"].to(torch.bfloat16).flatten()
    )
    run.get_buffer("weights_2").torch_view()[:] = (
        golden_ref["w_up"].to(torch.bfloat16).flatten()
    )
    run.get_buffer("weights_3").torch_view()[:] = (
        golden_ref["w_down"].to(torch.bfloat16).flatten()
    )

    # Correctness is checked on the FIRST run: creating the hw_context applies the
    # design's init CDO, so the first run on the freshly loaded full-ELF computes
    # correctly. The full-ELF path does not re-initialize the array between runs,
    # so later runs on the same callable read stale state and are used only for
    # timing below.
    #
    # The whole block is fused in bf16, so rounding accumulates and reorders across
    # the chain and the K=hidden_dim down-projection sum (near-cancellation
    # amplifies relative error): ~20% of elements drift past the 8% bound, so allow
    # up to 25%. Tolerances are local to this test.
    run()
    output = run.get_buffer("output").to_torch().reshape((seq_len, embedding_dim))
    errors = verify_buffer(
        output,
        "output",
        golden_ref["output"],
        rel_tol=0.08,
        abs_tol=0.7,
        max_error_rate=0.25,
    )
    assert not errors, f"Test failed with errors: {errors}"

    # Performance: time a run that reuses the hw_context, so it reflects the actual
    # kernel latency without the one-off ELF/hw_context setup.
    start = time.perf_counter()
    run()
    elapsed_us = (time.perf_counter() - start) * 1e6
    total_bytes = 2 * (seq_len * embedding_dim + seq_len * embedding_dim)  # bf16 in+out
    print(f"Latency (us): {elapsed_us:.2f}")
    print(f"Effective Bandwidth: {total_bytes / (elapsed_us * 1e-6) / 1e9:.4f} GB/s")


@pytest.mark.supported_devices("npu2")
@pytest.mark.metrics(
    Latency=r"Latency \(us\): (?P<value>[\d\.]+)",
    Bandwidth=r"Effective Bandwidth: (?P<value>[\d\.e\+-]+) GB/s",
)
@pytest.mark.parametrize(
    "seq_len,embedding_dim,hidden_dim,seq_tile,embedding_tile,hidden_tile", get_params()
)
def test_swiglu_prefill_stream(
    seq_len,
    embedding_dim,
    hidden_dim,
    seq_tile,
    embedding_tile,
    hidden_tile,
    aie_context,
):
    golden_ref = generate_golden_reference(M=seq_len, K=embedding_dim, N=hidden_dim)
    operator = SwiGLUPrefillStream(
        seq_len=seq_len,
        embedding_dim=embedding_dim,
        hidden_dim=hidden_dim,
        seq_len_tile_size=seq_tile,
        embedding_tile_size=embedding_tile,
        hidden_tile_size=hidden_tile,
        context=aie_context,
    )
    _run_and_verify(operator, seq_len, embedding_dim, golden_ref)


@pytest.mark.skipif(
    not _STREAM_HAS_SPLIT_GROUPS,
    reason="installed stream-dse lacks two-fusion-group support (split_groups)",
)
@pytest.mark.supported_devices("npu2")
@pytest.mark.metrics(
    Latency=r"Latency \(us\): (?P<value>[\d\.]+)",
    Bandwidth=r"Effective Bandwidth: (?P<value>[\d\.e\+-]+) GB/s",
)
@pytest.mark.parametrize(
    "seq_len,embedding_dim,hidden_dim,seq_tile,embedding_tile,hidden_tile", get_params()
)
def test_swiglu_prefill_stream_k2(
    seq_len,
    embedding_dim,
    hidden_dim,
    seq_tile,
    embedding_tile,
    hidden_tile,
    aie_context,
):
    golden_ref = generate_golden_reference(M=seq_len, K=embedding_dim, N=hidden_dim)
    operator = SwiGLUPrefillStreamK2(
        seq_len=seq_len,
        embedding_dim=embedding_dim,
        hidden_dim=hidden_dim,
        seq_len_tile_size=seq_tile,
        embedding_tile_size=embedding_tile,
        hidden_tile_size=hidden_tile,
        context=aie_context,
    )
    _run_and_verify(operator, seq_len, embedding_dim, golden_ref)
