# SPDX-FileCopyrightText: Copyright (C) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Test Pushing from a GitHub Action

on: 
 push:
 pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create some artifacts for testing
      run: |
        mkdir -p path/to/artifact/
        echo "This is a test artifact." > path/to/artifact/test_artifact.txt
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: path/to/artifact/ # or path/to/artifact
