name: "Test committing to private repo"

on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  upload_results:
    runs-on: ubuntu-latest

    steps:
      - name: Obtain existing results
        uses: actions/checkout@v4

      - name: Commit back results
        #if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          touch test
          git add -f test
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "test" || echo "No changes to commit"
          git push -u origin hallihallo